apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-k8s-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-k8s-sample
  template:
    metadata:
      labels:
        app: react-k8s-sample
    spec:
      containers:
      - name: react
        image: maheshkovuru/react-application
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: react-k8s-sample
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: react-k8s-sample
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: react-k8s-sample
